name: colbert
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - faiss-cpu
  - pip=21.0
  - pytorch-cpu=1.13
  - pip:
    - bitarray
    - datasets
    - gitpython
    - ninja
    - scipy
    - spacy
    - tqdm
    - transformers
    - ujson
    - flask
    - python-dotenv
