# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import splade_pb2 as splade__pb2


class SpladeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateQuery = channel.unary_unary(
                '/splade.Splade/GenerateQuery',
                request_serializer=splade__pb2.QueryStr.SerializeToString,
                response_deserializer=splade__pb2.QueryStr.FromString,
                )


class SpladeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpladeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateQuery,
                    request_deserializer=splade__pb2.QueryStr.FromString,
                    response_serializer=splade__pb2.QueryStr.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'splade.Splade', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Splade(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/splade.Splade/GenerateQuery',
            splade__pb2.QueryStr.SerializeToString,
            splade__pb2.QueryStr.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
