# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: splade.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csplade.proto\x12\x06splade\"-\n\x08QueryStr\x12\r\n\x05query\x18\x01 \x01(\t\x12\x12\n\nmultiplier\x18\x02 \x01(\x05\x32?\n\x06Splade\x12\x35\n\rGenerateQuery\x12\x10.splade.QueryStr\x1a\x10.splade.QueryStr\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'splade_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _QUERYSTR._serialized_start=24
  _QUERYSTR._serialized_end=69
  _SPLADE._serialized_start=71
  _SPLADE._serialized_end=134
# @@protoc_insertion_point(module_scope)
